### ISSUE TITLE
Index file on KStars - download disabled 

### ISSUE THREAD

**Issue by lbaffo** [MattBlack85/astroarch#2]
"Download disabled, director permission issue" when trying to download index file un usr/share/astrometry

**Comment by MattBlack85** [comment]
@lbaffo you should make a new directory `/home/astronaut/.local/share/astrometry` and download the files there to solve this issue, you need root permissions to write to /usr/share/astrometry`

**Comment by MattBlack85** [comment]
@lbaffo the newest version (you need to download it and flash it) has already a folder where the user `astronaut` has write access, you can pick it from the drop down menu

**Comment by MattBlack85** [comment]
fixed in the latest release `v1.0.0`
